### ISSUE TITLE
Minimum features required for first milestone of new itwêwina

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#205]
@eddieantonio @Madoshakalaka In order for us to release the new itwêwina, we need to implement the following minimum set of features:

- [ ] Step 0 - use latest dictionary content (XML) and latest improved FST (#255, #256, and #269).
- [x] Step 1 - AEW compliance
   - [x] 1. Presentation of orthographically standardized forms of search strings: exemplified in #209 and #224 (and earlier detailed in #100 and #140). 
   - [x] 2. Presentation of linguistic analysis (breakdown) as user-friendly tags: exemplified in #209 and #224 (and previously detailed in #153 and #99)
      - [x] 2.1. Presentation of linguistic analysis features as user-friendly tags.
      - [x] 2.2. Presentation of preverbs in linguistic breakdown/analyses and their opening out.

- [x] Step 2 - MESC compliance
   - [x] 3. Presentation of spoken recording snippets linked to the dictionary entry: detailed in #128 and #149.

Everything else than the tasks 1-3 above is priority-wise secondary (we do want to support syllabics and we do want proper prefix search on the Cree side, but those can wait until the above are implemented). If they are resolved quickly, then we can progress to task 4 below.

- [x] Step 3 - old itwêwina will not be needed anymore
   - [x] 4. Syllabics and both flavors of SRO are supported in presenting Cree content: detailed in #123

**Comment by aarppe** [comment]
A general note for interpreting the more detailed issues above. Since we've been working on the new itwêwina since the summer and our understanding of the functionalities has evolved over time, the earliest issues are best in addressing the overall general gist of the functionalities, and our views may and will have changed concerning whatever detail is presented. In this respect, the best reliable guidance on visual details can always be found in the very latest issue concerning a functionality.

We might well need to aggregate previous issues into new ones representing our current best understanding as well as laying out the details we've decided to focus on (alongside other nice things that might have turned obsolute or ones to be pursued later on with better time).

**Comment by aarppe** [comment]
Moved into its separate issue #296: _0. Visual organization of standardized forms, lemmas, definitions, linguistic breakdowns, etc., as detailed in #224 and #232._
