### ISSUE TITLE
Miscellaneous fixes

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#502]
A collection of observations that would benefit from some form of fix.

- [ ] 1. For II verbs, the general plain English relabeling of `+3Sg` in the linguistic analysis as `s/he` is not entirely appropriate. Solution: add `it` to the subjects?

- [x] 2. Turn the plain English relabeling of `+1Pl` into `we (but not you)` throughout the paradigms. **Resolved in:** #406 

- [x] 3. Add some missing imperative forms to AI/II verbs (e.g. `+1Pl`). **Resolved:** There is only an inclusive 1Pl imperative form.

**Comment by eddieantonio** [comment]
Closed in favor of #791
