### ISSUE TITLE
The way the test database is currently setup is... not ideal...

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#637]
Sub-issues:

 - [x] **the SQLite3 file should not be commited to the repo**
 - [x] the database management command should be converted to a regular Django management command (#639)
 - [x] the test database should be automatically recreated whenever `test_db_words.txt` changes

All of this stuff needs to be documented!

**Comment by eddieantonio** [comment]
Done. `wontfix` for automatic re-import of `test_db_words.txt`
