### ISSUE TITLE
Cree-to-English phrase translation: bugs, unsatisfying behavior, and suggestions for improvement

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/cree-intelligent-dictionary#694]
Now that we have testable version for providing English translated phrases matching the morphological features of Cree word forms within the extent presented in the full paradigms (for nouns and verbs), we can observe when it works as it should, and when it doesn't, and how it could otherwise improved. To check out this functionality, first log on to itwêwina at [itwêwina.altlab.app/admin](itwêwina.altlab.app/admin)

1. Functionality
- [ ] Consider showing a generated translation even in the case that the word forms incorporates (lexical) preverbs for which no translation is generated. For instance, _nipê-nipân_ -> _PV/pê+_ + _I sleep._ **MD** 🤖 + _I sleep, I am asleep_ **CW** 🤖 - Alternatively, generated translations are provided only for exact matches of Cree word forms.

2. Appearance
- [ ] Indicate the synthetic nature of the generated English phrases with the robot-head symbol: 🤖
- [ ] Indicate both the source of the English translation (CW or MD) as well as the synthetic nature, i.e. **CW** 🤖 or **MD** 🤖
- [ ] Do not show generated translations for Cree word forms that are lemmas.
- [ ] Do not show a generated translation for a non-lemma Cree word-form when a manual translation has been provided for the particular inflected Cree word form OR
- [ ] show both the generated and manually provided translations for such word forms, but exclude generated translations when they are practically the same as the manual ones, cf. 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/15003407/111013796-13f63880-835e-11eb-94e4-88561011fc7c.png">
- [ ] Show Cree word form and generated English translation before the lemma and its manual translation.
